/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jcurses_system_KeyDefs */

#ifndef _Included_jcurses_system_KeyDefs
#define _Included_jcurses_system_KeyDefs
#ifdef __cplusplus
extern "C" {
#endif
#undef jcurses_system_KeyDefs_KEY_UP
#define jcurses_system_KeyDefs_KEY_UP 10L
#undef jcurses_system_KeyDefs_KEY_DOWN
#define jcurses_system_KeyDefs_KEY_DOWN 20L
#undef jcurses_system_KeyDefs_KEY_LEFT
#define jcurses_system_KeyDefs_KEY_LEFT 30L
#undef jcurses_system_KeyDefs_KEY_RIGHT
#define jcurses_system_KeyDefs_KEY_RIGHT 40L
#undef jcurses_system_KeyDefs_KEY_BACKSPACE
#define jcurses_system_KeyDefs_KEY_BACKSPACE 50L
#undef jcurses_system_KeyDefs_KEY_DELETE
#define jcurses_system_KeyDefs_KEY_DELETE 60L
#undef jcurses_system_KeyDefs_KEY_HOME
#define jcurses_system_KeyDefs_KEY_HOME 70L
#undef jcurses_system_KeyDefs_KEY_END
#define jcurses_system_KeyDefs_KEY_END 80L
#undef jcurses_system_KeyDefs_KEY_PGUP
#define jcurses_system_KeyDefs_KEY_PGUP 90L
#undef jcurses_system_KeyDefs_KEY_PGDOWN
#define jcurses_system_KeyDefs_KEY_PGDOWN 100L
#undef jcurses_system_KeyDefs_CTYPE_UNKNOWN
#define jcurses_system_KeyDefs_CTYPE_UNKNOWN 0L
#undef jcurses_system_KeyDefs_CTYPE_PRINTABLE
#define jcurses_system_KeyDefs_CTYPE_PRINTABLE 1L
#undef jcurses_system_KeyDefs_CTYPE_CONTROL
#define jcurses_system_KeyDefs_CTYPE_CONTROL 2L
#undef jcurses_system_KeyDefs_CTYPE_FUNCTION
#define jcurses_system_KeyDefs_CTYPE_FUNCTION 4L
#undef jcurses_system_KeyDefs_CTYPE_ERROR
#define jcurses_system_KeyDefs_CTYPE_ERROR 8L
#ifdef __cplusplus
}
#endif
#endif
